/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_line_comment = 2,
  sym__automatic_semicolon = 3,
  sym__slashy_string_start = 4,
  sym__slashy_string_body = 5,
  sym__slashy_string_end = 6,
  sym__dollar_slashy_string = 7,
  sym__gstring_body = 8,
  sym__gstring_interpolation_start = 9,
  sym__label_colon = 10,
  sym_block_comment = 11,
  sym_groovydoc_comment = 12,
  sym_source_file = 13,
  sym__statement = 14,
  aux_sym_source_file_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_line_comment] = "line_comment",
  [sym__automatic_semicolon] = "_automatic_semicolon",
  [sym__slashy_string_start] = "_slashy_string_start",
  [sym__slashy_string_body] = "_slashy_string_body",
  [sym__slashy_string_end] = "_slashy_string_end",
  [sym__dollar_slashy_string] = "_dollar_slashy_string",
  [sym__gstring_body] = "_gstring_body",
  [sym__gstring_interpolation_start] = "_gstring_interpolation_start",
  [sym__label_colon] = "_label_colon",
  [sym_block_comment] = "block_comment",
  [sym_groovydoc_comment] = "groovydoc_comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_line_comment] = sym_line_comment,
  [sym__automatic_semicolon] = sym__automatic_semicolon,
  [sym__slashy_string_start] = sym__slashy_string_start,
  [sym__slashy_string_body] = sym__slashy_string_body,
  [sym__slashy_string_end] = sym__slashy_string_end,
  [sym__dollar_slashy_string] = sym__dollar_slashy_string,
  [sym__gstring_body] = sym__gstring_body,
  [sym__gstring_interpolation_start] = sym__gstring_interpolation_start,
  [sym__label_colon] = sym__label_colon,
  [sym_block_comment] = sym_block_comment,
  [sym_groovydoc_comment] = sym_groovydoc_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__automatic_semicolon] = {
    .visible = false,
    .named = true,
  },
  [sym__slashy_string_start] = {
    .visible = false,
    .named = true,
  },
  [sym__slashy_string_body] = {
    .visible = false,
    .named = true,
  },
  [sym__slashy_string_end] = {
    .visible = false,
    .named = true,
  },
  [sym__dollar_slashy_string] = {
    .visible = false,
    .named = true,
  },
  [sym__gstring_body] = {
    .visible = false,
    .named = true,
  },
  [sym__gstring_interpolation_start] = {
    .visible = false,
    .named = true,
  },
  [sym__label_colon] = {
    .visible = false,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_groovydoc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '/') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym__automatic_semicolon] = ACTIONS(1),
    [sym__slashy_string_start] = ACTIONS(1),
    [sym__slashy_string_body] = ACTIONS(1),
    [sym__slashy_string_end] = ACTIONS(1),
    [sym__dollar_slashy_string] = ACTIONS(1),
    [sym__gstring_body] = ACTIONS(1),
    [sym__gstring_interpolation_start] = ACTIONS(1),
    [sym__label_colon] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(3),
    [sym_groovydoc_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [sym__statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_groovydoc_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_identifier,
    STATE(3), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    ACTIONS(3), 3,
      sym_block_comment,
      sym_groovydoc_comment,
      sym_line_comment,
  [16] = 4,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(3), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    ACTIONS(3), 3,
      sym_block_comment,
      sym_groovydoc_comment,
      sym_line_comment,
  [32] = 2,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_block_comment,
      sym_groovydoc_comment,
      sym_line_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 32,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [18] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__automatic_semicolon = 0,
  ts_external_token__slashy_string_start = 1,
  ts_external_token__slashy_string_body = 2,
  ts_external_token__slashy_string_end = 3,
  ts_external_token__dollar_slashy_string = 4,
  ts_external_token__gstring_body = 5,
  ts_external_token__gstring_interpolation_start = 6,
  ts_external_token__label_colon = 7,
  ts_external_token_block_comment = 8,
  ts_external_token_groovydoc_comment = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__automatic_semicolon] = sym__automatic_semicolon,
  [ts_external_token__slashy_string_start] = sym__slashy_string_start,
  [ts_external_token__slashy_string_body] = sym__slashy_string_body,
  [ts_external_token__slashy_string_end] = sym__slashy_string_end,
  [ts_external_token__dollar_slashy_string] = sym__dollar_slashy_string,
  [ts_external_token__gstring_body] = sym__gstring_body,
  [ts_external_token__gstring_interpolation_start] = sym__gstring_interpolation_start,
  [ts_external_token__label_colon] = sym__label_colon,
  [ts_external_token_block_comment] = sym_block_comment,
  [ts_external_token_groovydoc_comment] = sym_groovydoc_comment,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__automatic_semicolon] = true,
    [ts_external_token__slashy_string_start] = true,
    [ts_external_token__slashy_string_body] = true,
    [ts_external_token__slashy_string_end] = true,
    [ts_external_token__dollar_slashy_string] = true,
    [ts_external_token__gstring_body] = true,
    [ts_external_token__gstring_interpolation_start] = true,
    [ts_external_token__label_colon] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_groovydoc_comment] = true,
  },
  [2] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_groovydoc_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_groovy_external_scanner_create(void);
void tree_sitter_groovy_external_scanner_destroy(void *);
bool tree_sitter_groovy_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_groovy_external_scanner_serialize(void *, char *);
void tree_sitter_groovy_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_groovy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_groovy_external_scanner_create,
      tree_sitter_groovy_external_scanner_destroy,
      tree_sitter_groovy_external_scanner_scan,
      tree_sitter_groovy_external_scanner_serialize,
      tree_sitter_groovy_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "groovy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
